# **PRACTICAL 4**
# **Write a NumPy program to implement following operation**

In [1]:
import numpy as np

**1. To add, subtract, multiply, divide arguments element-wise**

In [2]:
arr = np.random.randint(100,109,(3,3))
print("The array is : \n",arr)
print(f"array + {2} : \n{arr+2}")
print(f"array - {2} : \n{arr-2}")
print(f"array * {2} : \n{arr*2}")
div = arr / 7
print(f"array / {7} : \n{div}")

The array is : 
 [[101 100 102]
 [101 102 104]
 [105 101 104]]
array + 2 : 
[[103 102 104]
 [103 104 106]
 [107 103 106]]
array - 2 : 
[[ 99  98 100]
 [ 99 100 102]
 [103  99 102]]
array * 2 : 
[[202 200 204]
 [202 204 208]
 [210 202 208]]
array / 7 : 
[[14.42857143 14.28571429 14.57142857]
 [14.42857143 14.57142857 14.85714286]
 [15.         14.42857143 14.85714286]]


**2.  To round elements of the array to the nearest integer**

In [3]:
rou = np.round(div)
print("The without rounded array is : \n",div)
print("The rounded array is : \n",rou)

The without rounded array is : 
 [[14.42857143 14.28571429 14.57142857]
 [14.42857143 14.57142857 14.85714286]
 [15.         14.42857143 14.85714286]]
The rounded array is : 
 [[14. 14. 15.]
 [14. 15. 15.]
 [15. 14. 15.]]


**3. To calculate mean across dimension, in a 2D numpy array**

In [4]:
array2D = np.arange(1,10).reshape(3,3)
print("The 2D array is : \n",array2D)
print("The mean operation of full array : \n",np.mean(array2D))
print("The mean operation of array row by row (axis = 0) : \n",np.mean(array2D,axis=0))
print("The mean operation of array column by column (axis = 1) : \n",np.mean(array2D,axis=1))

The 2D array is : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The mean operation of full array : 
 5.0
The mean operation of array row by row (axis = 0) : 
 [4. 5. 6.]
The mean operation of array column by column (axis = 1) : 
 [2. 5. 8.]


**4. To calculate the difference between neighboring elements, elementwise of a given array**

In [5]:
array1D = np.random.randint(100,size = 6)
print("The array is : \n",array1D)
print("The difference between neighboring elements : \n",np.ediff1d(array1D))

The array is : 
 [86 11 82 53 83 53]
The difference between neighboring elements : 
 [-75  71 -29  30 -30]
