# **PRACTICAL 3**
# **Write a NumPy program to implement following operation**

In [1]:
import numpy as np

**1. To split an array of 14 elements into 3 arrays, each with 2, 4, and 8
elements in the original order**

In [2]:
arr = np.arange(1,15)
print("The main array is : ")
print(arr)
split1, split2, split3 = np.split(arr,[2,6])
print("The splited array 1 : ")
print(split1)
print("The splited array 2 : ")
print(split2)
print("The splited array 3 : ")
print(split3)

The main array is : 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
The splited array 1 : 
[1 2]
The splited array 2 : 
[3 4 5 6]
The splited array 3 : 
[ 7  8  9 10 11 12 13 14]


**2. To stack arrays horizontally (column wise)**

In [3]:
arr1 = np.arange(1,7).reshape(2,3)
print("The first array is : \n",arr1)
arr2 = np.arange(7,13).reshape(2,3)
print("The second array is : \n",arr2)
arr3 = np.hstack([arr1,arr2])
print("The stacked array is : \n",arr3)

The first array is : 
 [[1 2 3]
 [4 5 6]]
The second array is : 
 [[ 7  8  9]
 [10 11 12]]
The stacked array is : 
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
