# **PRACTICAL 2**
# ***Write a NumPy program to implement following operation***

In [1]:
import numpy as np

**1. To convert a list of numeric values into a one-dimensional NumPy
array**

In [2]:
num_list = [1,2,3,4,5,6,7,8,9,10]
print(f"The list is : \n{num_list}")
odArray = np.array(num_list)
print(f"The NumPY array is : ")
odArray

The list is : 
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
The NumPY array is : 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**2. To create a 3x3 matrix with values ranging from 2 to 10**

In [3]:
matrix = np.random.randint(2,11,(3,3))
print(matrix)

[[ 3  9  4]
 [ 2  3  5]
 [ 8 10  2]]


**3. To append values at the end of an array**

In [4]:
arr = np.array([1,2,3,4,5])
print(f"Without Appending the value : ")
print(arr)
arr = np.append(arr,[6,7,8,9,10])
print("With Appending the value : ")
arr

Without Appending the value : 
[1 2 3 4 5]
With Appending the value : 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**4. To create another shape from an array without changing its data(3\*2
to 2\*3)**

In [5]:
array = np.array([1,2,3,4,5,6]).reshape(3,2)
print("The array in 3*2 shape : ")
print(array)
print("The array in 2*3 shape : ")
array = array.reshape(2,3)
print(array)

The array in 3*2 shape : 
[[1 2]
 [3 4]
 [5 6]]
The array in 2*3 shape : 
[[1 2 3]
 [4 5 6]]
