# **PRACTICAL 5**
# **Write a NumPy program to implement following operation**

In [1]:
import numpy as np

**1. To find the maximum and minimum value of a given flattened array**

In [2]:
arr = np.random.randint(1,100,(3,3))
print("The original array is : \n",arr)
arr = arr.flatten()
print("The flattened array is : \n",arr)
print("The maximum value in array is : \n",np.max(arr))
print("The minimum value in array is : \n",np.min(arr))

The original array is : 
 [[57 55 24]
 [73 18 85]
 [39  2 95]]
The flattened array is : 
 [57 55 24 73 18 85 39  2 95]
The maximum value in array is : 
 95
The minimum value in array is : 
 2


**2. To compute the mean, standard deviation, and variance of a given
array along the second axis**

In [3]:
array = np.random.randint(1,100,(3,3))
print("The array is : \n",array)
print("The mean of the array along the second axis is : \n",np.mean(array,axis=1))
print("The standard deviation of the array along the second axis is : \n",np.std(array,axis=1))
print("The variance of the array along the second axis is : \n",np.var(array,axis=1))

The array is : 
 [[92 30 56]
 [74 65  5]
 [82 76 36]]
The mean of the array along the second axis is : 
 [59.33333333 48.         64.66666667]
The standard deviation of the array along the second axis is : 
 [25.42090129 30.62678566 20.41785711]
The variance of the array along the second axis is : 
 [646.22222222 938.         416.88888889]
